WebApp/Models/GameRandom.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public class GameRandom
    {
        public static string MatchGuess(int guess, int rnd)
        {
            if (guess < rnd)
            {
                return "HigherTemp!";
            }
            else if (guess > rnd)
            {
                return "LowerTemp!";
            }
            else
            {
                return "Yes!! You won!";
            }
        }
        public static int GetRandom(int max)
        {
            Random rnd = new Random();
            return rnd.Next(1, max);
        }
    }
}

WebApp/Models/TempFever.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppAsa.Models
{
    public class FeverTemp
    {
        public static string TestForFever(float temperature)
        {
            //double dubbleTemp = new double();

            return (temperature > 37) ? "...have a cookie" : "Doctor says your temperature is nornal you don't have Fever...so no cookie";
        }
    }

}
 

WebApp/Controllers/DoctorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Controllers
{
    public class DoctorController : Controller
    {
        [HttpGet]
        public IActionResult TempCheck(float temp)
        {
            
          if (temp != 0)
            {
                ViewBag.Msg = Models.FeverTemp.TestForFever(temp);
                return View();
            }
            else
            {
                ViewBag.Msg = "Pls enter your temperaure and then hit Submit";
                return View();
            }
        }
        [HttpGet]
        public IActionResult TempFever()
        {
            return View();
        }

    }
}

/*
Create new Controller named Doctor to the existing MVC-project and inside it make a View that 
takes a temperature in number form, checks how high it is, and tells you whether you have a 
fever or not. 
Required Features: 
• A form that takes a single numeric value (float or integer) and sends it on to a controller 
action. 
• The value should be interpreted as a temperature, and checked against the thresholds 
for fever. 
• A message should appear on the page, showing whether you have a fever or not. 
Optional:  
• Add a check for hypothermia as well as fever, and display that as a message if you have a too low 
temperature.  
• Add radio buttons to allow switching between Fahrenheit and Celsius degrees. 
Code Requirements:  
• The view must have a form that sends the value into the action. 
• If the value is not set, the page should not get a message to display, otherwise it should 
evaluate it and send back the message. 
• A custom route must be defined for this view. 
• The view must be from an Action inside Doctor controller. 
• The code checking the temperature and giving the diagnose text back must be in a utility 
class with a static method, contained in Models folder. 
• Define a custom route to reach the fever check “/FeverCheck”, rather than having to 
specify a controller and action 
 */

WebApp/Controllers/GameController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Models;
using WebAppAsa.Models;

namespace WebAppAsa.Controllers
{
    public class GameController : Controller
    {
        [HttpPost]
        public IActionResult GuessGame(int userGuess)
        {
            if (!(string.IsNullOrEmpty(HttpContext.Session.GetString("intRnd")) || userGuess <= 0 || userGuess >= 100))
            {
                int storedRnd = (int)HttpContext.Session.GetInt32("intRnd");
                string respons = GameRandom.MatchGuess(Convert.ToInt32(userGuess), storedRnd);
                ViewBag.Msg = respons;
            }
            else
            {
                ViewBag.Msg = "Enter a number between 1 and 100 and Submit";
            }
            return View();
        }

        [HttpGet]
        public IActionResult GuessingGame()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("intRnd")))
            {
                int getRnd = GameRandom.GetRandom(100);
                HttpContext.Session.SetInt32("intRnd", getRnd);
                ViewBag.Rnd = getRnd;
            }
            else
            {
                ViewBag.Rnd = HttpContext.Session.GetInt32("intRnd");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Reset()
        {
            int getRnd = GameRandom.GetRandom(100);
            HttpContext.Session.SetInt32("intRnd", getRnd);
            ViewBag.Rnd = getRnd;
            return RedirectToAction(nameof(GuessGame));
        }
    }
}

WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppAsa.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()// Get 
        {
            return View();// print out reslt
        }
        public IActionResult About()//Get
        {
            return View();//print out reslt
        }
        public IActionResult Contact()//post
        {
            return View();//print out reslt
        }
        public IActionResult Portfolio()//Get
        {
            return View();//print out reslt
        }

    }
}

WebApp/Views/Doctor/FeverCheck.cshtml
@{
    ViewData["Title"] = "Your Temperature Fever Checkup";
}

<div class="container">
    <h2>checking out you bodytemprature</h2>
    <div class="wrapper">

        <h3>Fever Check</h3>
        <form asp-action="FeverCheck" asp-controller="Doctor" method="post">

            <input type="number" name="temp" value="" placeholder="Please enter your body temperature" min="32" max="43" step="0.1" />
            <button type="submit">Submit</button>

            <p>
                @if (ViewBag.Msg != null)
                {@ViewBag.Msg}
            </p>
        </form>
    </div>
</div>

@if (ViewBag.tempMsg != null)
{
<p>Temp result: @ViewBag.tempMsg</p>

}

WebApp/Views/Game/GuessingGame.cshtml
@{
    ViewData["Title"] = "GuessingGame";
}

<h1>Guessing game</h1>

<div class="wrapper">
    <p>Guess a number between 1 and 100.</p>
    <p>Good Luck</p>
    <div class="card">
        <form asp-action="GuessingGame" asp-controller="Game" method="post">

            <input type="number" name="userGuess" value="" placeholder="Enter a number between 1 and 100 number" min="1" max="101" />
            <br />
            <br />
            <button class="gameButton" type="submit">Submit</button>
            <br />
            <p>
                @if (ViewBag.Msg != null)
                {@ViewBag.Msg}
            </p>

            <p>
                @if (ViewBag.Rnd != null)
                {@ViewBag.Rad}
            </p>
        </form>
        <br />
        <form asp-action="Reset" asp-controller="Game" method="get">
            <button class="resetbutton">Reset</button>
            <br />
        </form>
    </div>
</div>

WebApp/Views/Home/Aboutus.cshtml
@{
    ViewData["Title"] = "About me";
}

<section class="wrapper">
    <h1>About... My CV</h1>
    <article class="card">
        <h3> Halmstad University Network security</h3>
        <p>
            2018 feb-june
            CISCO Advanced Routing 7.50HP DT4005, Converged Optimized Networks
        </p>
    </article>
    <article class="card">
        <h3>Linnus University, Växjö Exchange student (2015-2016)</h3>
        <p>
            Mobile and wireless data security, User interface design
        </p>
    </article>
    <article class="card">
        <h3>Mykolas Romeris University, Vilnius Lithuania </h3>
        <p>
            Business informatics. Field of Study Information Technology (2013 – 2017)
        </p>
    </article>
    <article class="card">
        <h3>Middlesex University, United Kingdom.</h3>
        <p>
            Bachelor of Applied Science (BSC), Business Informatics (2013 – 2017)
        </p>
 
    <
    </article>
</section>

WebApp/Views/Home/Contact.cshtml
@{ ViewData["Title"] = "Contact"; }


<h1>Contact</h1>
<div class="wrapper">
    <section class="card">
        <p>Name:Emmanuel Umoren</p>
        <p>Phone: 0729283209 </p>
    </section>

</div>

WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Welcome...</h1>
<div class="wrapper">
    <div class="card">
        <h2>...to the dark side</h2>
        <h2Do you prefer action reminder formaction checkups?</h2>
        <h5>WE HAVE COOKIES</h5>
    </div>
</div>

WebApp/Views/Home/portfolio.cshtml
@{ ViewData["Title"] = "Portfolio"; }

<h1>Portfolio</h1>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/css/Site.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <footer></footer>
</body>
</html>